export interface CoupleChallenge {
  id: number;
  category: "comunicacion" | "aventura" | "romantico" | "divertido" | "intimo" | "creatividad" | "crecimiento";
  challenge: string;
  emoji: string;
}

export const COUPLE_CHALLENGES: CoupleChallenge[] = [
  { id: 1, category: "comunicacion", challenge: "Dile a tu pareja tres cosas que admiras de ella que nunca le hayas dicho.", emoji: "💬" },
  { id: 2, category: "aventura", challenge: "Salgan a caminar juntos por un lugar nuevo del barrio que nunca hayan explorado.", emoji: "🗺️" },
  { id: 3, category: "romantico", challenge: "Escríbele una carta corta de amor en un papel y escóndela donde la encuentre.", emoji: "💌" },
  { id: 4, category: "divertido", challenge: "Hagan una competencia de baile con su canción favorita. El que pierda prepara el café.", emoji: "💃" },
  { id: 5, category: "intimo", challenge: "Mírense a los ojos durante 2 minutos sin hablar. Solo sientan la conexión.", emoji: "👀" },
  { id: 6, category: "creatividad", challenge: "Dibujen un retrato el uno del otro, no importa si no saben dibujar.", emoji: "🎨" },
  { id: 7, category: "crecimiento", challenge: "Compartan un miedo o inseguridad que no hayan mencionado antes.", emoji: "🌱" },
  { id: 8, category: "comunicacion", challenge: "Pregúntale: ¿Cuál es tu recuerdo favorito de nosotros? Escucha sin interrumpir.", emoji: "🗣️" },
  { id: 9, category: "aventura", challenge: "Vayan juntos al Malecón al atardecer y quédense hasta que salgan las estrellas.", emoji: "🌅" },
  { id: 10, category: "romantico", challenge: "Prepárale el desayuno en la cama, aunque sea un café con galleticas.", emoji: "☕" },
  { id: 11, category: "divertido", challenge: "Jueguen al 'teléfono descompuesto' pero solo ustedes dos, inventando historias locas.", emoji: "😂" },
  { id: 12, category: "intimo", challenge: "Dense un abrazo largo de al menos 30 segundos. Sin prisa, solo sintiendo.", emoji: "🤗" },
  { id: 13, category: "creatividad", challenge: "Inventen juntos una canción sobre su historia de amor, aunque sea de una sola estrofa.", emoji: "🎵" },
  { id: 14, category: "crecimiento", challenge: "Digan cada uno algo que les gustaría mejorar de sí mismos, y apóyense mutuamente.", emoji: "💪" },
  { id: 15, category: "comunicacion", challenge: "Envíale un mensaje de voz diciéndole por qué te enamoraste de ella/él.", emoji: "🎙️" },
  { id: 16, category: "aventura", challenge: "Cocinen juntos una receta nueva que ninguno haya probado antes.", emoji: "👨‍🍳" },
  { id: 17, category: "romantico", challenge: "Pongan su canción y bailen juntos en la sala, como si nadie los viera.", emoji: "🩰" },
  { id: 18, category: "divertido", challenge: "Hagan una sesión de fotos graciosas juntos, con las poses más ridículas posibles.", emoji: "📸" },
  { id: 19, category: "intimo", challenge: "Cuéntale cuál fue el momento exacto en que supiste que estabas enamorado/a.", emoji: "💕" },
  { id: 20, category: "creatividad", challenge: "Hagan un collage con recortes de revista sobre sus sueños como pareja.", emoji: "✂️" },
  { id: 21, category: "crecimiento", challenge: "Hablen sobre dónde se ven juntos en 5 años. Sean sinceros y soñadores.", emoji: "🔮" },
  { id: 22, category: "comunicacion", challenge: "Jueguen a '20 preguntas' pero solo preguntas sobre el otro. Sorpréndanse.", emoji: "❓" },
  { id: 23, category: "aventura", challenge: "Visiten una heladería que no conozcan y prueben el sabor más raro del menú.", emoji: "🍦" },
  { id: 24, category: "romantico", challenge: "Dile un piropo cubano bien original que se te ocurra en el momento.", emoji: "😍" },
  { id: 25, category: "divertido", challenge: "Imiten al otro. Cada uno hace de su pareja por 5 minutos. ¡Sin ofenderse!", emoji: "🎭" },
  { id: 26, category: "intimo", challenge: "Lean juntos algo bonito: un poema, una canción, o un texto que les guste a los dos.", emoji: "📖" },
  { id: 27, category: "creatividad", challenge: "Escriban cada uno en un papel 5 cosas que agradecen del otro e intercámbienlos.", emoji: "✍️" },
  { id: 28, category: "crecimiento", challenge: "Pídele perdón por algo pequeño que hayas hecho y que tal vez no notaste.", emoji: "🕊️" },
  { id: 29, category: "comunicacion", challenge: "Cuéntale qué parte de tu día fue la mejor y cuál la peor. Escúchense con atención.", emoji: "📝" },
  { id: 30, category: "aventura", challenge: "Hagan un picnic improvisado, aunque sea en el piso de la casa con lo que haya.", emoji: "🧺" },
  { id: 31, category: "romantico", challenge: "Dedícale una canción. Ponla y dile: 'Esta me recuerda a ti porque...'", emoji: "🎶" },
  { id: 32, category: "divertido", challenge: "Jueguen piedra, papel o tijera. El que pierda 3 veces tiene que hacer un favor al otro.", emoji: "✊" },
  { id: 33, category: "intimo", challenge: "Hablen de lo que más les gusta de la intimidad entre ustedes. Sin tabúes.", emoji: "🔥" },
  { id: 34, category: "creatividad", challenge: "Hagan un TikTok o video corto juntos haciendo algo divertido.", emoji: "🎬" },
  { id: 35, category: "crecimiento", challenge: "Lean juntos un artículo sobre relaciones y comenten qué les resonó.", emoji: "📰" },
  { id: 36, category: "comunicacion", challenge: "Dile algo que te cueste decir pero que sientes profundamente.", emoji: "❤️" },
  { id: 37, category: "aventura", challenge: "Caminen bajo la lluvia tropical juntos. Déjense mojar y rían.", emoji: "🌧️" },
  { id: 38, category: "romantico", challenge: "Escríbele un mini poema: no tiene que rimar, solo tiene que ser de corazón.", emoji: "📜" },
  { id: 39, category: "divertido", challenge: "Hagan un karaoke improvisado en casa. Canten a todo pulmón sin vergüenza.", emoji: "🎤" },
  { id: 40, category: "intimo", challenge: "Dense un masaje de manos por 5 minutos cada uno. Solo las manos.", emoji: "🤲" },
  { id: 41, category: "creatividad", challenge: "Pinten o coloreen algo juntos. Puede ser un mandala o cualquier dibujo.", emoji: "🖌️" },
  { id: 42, category: "crecimiento", challenge: "Hablen de un momento difícil que superaron juntos y cómo los hizo más fuertes.", emoji: "⛰️" },
  { id: 43, category: "comunicacion", challenge: "Pregúntale: ¿Hay algo que necesites de mí que no te he dado últimamente?", emoji: "💭" },
  { id: 44, category: "aventura", challenge: "Exploren una parte de La Habana que no conozcan. Descubran algo nuevo.", emoji: "🏛️" },
  { id: 45, category: "romantico", challenge: "Sorpréndele con su dulce favorito hoy. Sin razón, solo porque la/lo quieres.", emoji: "🍬" },
  { id: 46, category: "divertido", challenge: "Cuenten chistes malísimos hasta que uno de los dos se ría de verdad.", emoji: "🤣" },
  { id: 47, category: "intimo", challenge: "Acuéstense juntos y escuchen los latidos del corazón del otro.", emoji: "💗" },
  { id: 48, category: "creatividad", challenge: "Creen una playlist conjunta con 10 canciones que definan su relación.", emoji: "🎧" },
  { id: 49, category: "crecimiento", challenge: "Establezcan una meta como pareja para este mes y planifiquen cómo lograrla.", emoji: "🎯" },
  { id: 50, category: "comunicacion", challenge: "Cuéntale sobre la persona que más ha influido en tu vida y por qué.", emoji: "👤" },
  { id: 51, category: "aventura", challenge: "Hagan ejercicio juntos: correr, flexiones, yoga o lo que quieran.", emoji: "🏃" },
  { id: 52, category: "romantico", challenge: "Vean juntos el amanecer. Madrugar vale la pena cuando es con tu persona.", emoji: "🌄" },
  { id: 53, category: "divertido", challenge: "Jueguen al 'yo nunca nunca' y descubran cosas nuevas del otro.", emoji: "🙈" },
  { id: 54, category: "intimo", challenge: "Dile exactamente qué es lo que más te atrae físicamente de ella/él.", emoji: "✨" },
  { id: 55, category: "creatividad", challenge: "Escriban juntos la historia de cómo se conocieron, cada uno añadiendo una línea.", emoji: "📕" },
  { id: 56, category: "crecimiento", challenge: "Hablen sobre un hábito que cada uno quiera desarrollar y comprométanse a apoyarse.", emoji: "🌿" },
  { id: 57, category: "comunicacion", challenge: "Dile 'gracias' por 5 cosas específicas que haya hecho esta semana.", emoji: "🙏" },
  { id: 58, category: "aventura", challenge: "Prueben a hacer un postre cubano juntos: flan, natilla, o arroz con leche.", emoji: "🍮" },
  { id: 59, category: "romantico", challenge: "Tómense de las manos y caminen en silencio 10 minutos. Solo presencia.", emoji: "🤝" },
  { id: 60, category: "divertido", challenge: "Hagan una guerra de cosquillas. El primero en rendirse pierde.", emoji: "😜" },
  { id: 61, category: "intimo", challenge: "Hablen sobre un sueño o fantasía que tengan juntos para el futuro.", emoji: "🌟" },
  { id: 62, category: "creatividad", challenge: "Armen un rompecabezas juntos o jueguen dominó como buenos cubanos.", emoji: "🁡" },
  { id: 63, category: "crecimiento", challenge: "Perdónense mutuamente por algo pendiente. Libérense de ese peso.", emoji: "☮️" },
  { id: 64, category: "comunicacion", challenge: "Escuchen juntos un podcast sobre parejas y comenten lo que aprendieron.", emoji: "🎧" },
  { id: 65, category: "aventura", challenge: "Hagan un recorrido por los murales de Callejón de Hamel y saquen fotos.", emoji: "🎨" },
  { id: 66, category: "romantico", challenge: "Mírale y dile: 'Eres la mejor decisión que he tomado.'", emoji: "💘" },
  { id: 67, category: "divertido", challenge: "Cocinen algo intercambiando roles: quien nunca cocina, cocina hoy.", emoji: "🍳" },
  { id: 68, category: "intimo", challenge: "Quédense acurrucados 15 minutos sin teléfono. Solo ustedes.", emoji: "🛋️" },
  { id: 69, category: "creatividad", challenge: "Tomen una foto juntos recreando una foto vieja de cuando empezaron.", emoji: "📷" },
  { id: 70, category: "crecimiento", challenge: "Hablen de cómo manejan los conflictos y qué podrían mejorar.", emoji: "🤔" },
  { id: 71, category: "comunicacion", challenge: "Completa la frase: 'Me siento más amado/a cuando tú...' y escúchense.", emoji: "💬" },
  { id: 72, category: "aventura", challenge: "Vayan a la playa más cercana y metan los pies en el agua juntos.", emoji: "🏖️" },
  { id: 73, category: "romantico", challenge: "Haz algo que sabes que tu pareja necesita hoy sin que te lo pida.", emoji: "🎁" },
  { id: 74, category: "divertido", challenge: "Intercambien teléfonos por 10 minutos. ¿Qué encontrarán?", emoji: "📱" },
  { id: 75, category: "intimo", challenge: "Dile cuál es tu lenguaje del amor principal y cómo le gustaría que lo expresen.", emoji: "💝" },
  { id: 76, category: "creatividad", challenge: "Hagan origami juntos. Busquen un tutorial y doblen grullas o corazones.", emoji: "🦢" },
  { id: 77, category: "crecimiento", challenge: "Escriban cada uno una carta a su 'yo del futuro' como pareja.", emoji: "✉️" },
  { id: 78, category: "comunicacion", challenge: "Jueguen a completar: 'Lo que más me gusta de nuestros domingos es...'", emoji: "☀️" },
  { id: 79, category: "aventura", challenge: "Salgan en bici o a pie a buscar el mejor batido de la zona.", emoji: "🥤" },
  { id: 80, category: "romantico", challenge: "Pon música romántica y cénale a la luz de velas (aunque sea con una velita).", emoji: "🕯️" },
  { id: 81, category: "divertido", challenge: "Hagan una lista de 'Las 10 cosas más graciosas que nos han pasado'.", emoji: "📋" },
  { id: 82, category: "intimo", challenge: "Acuéstense frente a frente y cuéntense lo que más los hace sentir seguros.", emoji: "🛏️" },
  { id: 83, category: "creatividad", challenge: "Inventen un handshake secreto solo de ustedes dos.", emoji: "🤜" },
  { id: 84, category: "crecimiento", challenge: "Lean cada uno un capítulo de un libro y cuéntenselo al otro.", emoji: "📚" },
  { id: 85, category: "comunicacion", challenge: "Pregúntale: ¿Qué puedo hacer para hacerte sentir más especial?", emoji: "🌹" },
  { id: 86, category: "aventura", challenge: "Paseen por el Vedado de noche y descubran lugares con buena vibra.", emoji: "🌙" },
  { id: 87, category: "romantico", challenge: "Dale un beso en la frente cuando menos se lo espere hoy.", emoji: "😘" },
  { id: 88, category: "divertido", challenge: "Hagan un reto de 'no reírse' viéndose a la cara 3 minutos.", emoji: "😐" },
  { id: 89, category: "intimo", challenge: "Confiésale algo bonito que piensas sobre ella/él pero que nunca dices.", emoji: "🥺" },
  { id: 90, category: "creatividad", challenge: "Creen juntos un meme sobre su relación.", emoji: "😄" },
  { id: 91, category: "crecimiento", challenge: "Hablen sobre qué valores son innegociables para cada uno en la relación.", emoji: "⚖️" },
  { id: 92, category: "comunicacion", challenge: "Dile lo primero que pensaste cuando la/lo viste por primera vez.", emoji: "👋" },
  { id: 93, category: "aventura", challenge: "Vayan a un lugar con vista panorámica y contemplen La Habana desde arriba.", emoji: "🏙️" },
  { id: 94, category: "romantico", challenge: "Envíale un mensaje a medianoche que diga: 'Buenas noches, vida mía.'", emoji: "🌜" },
  { id: 95, category: "divertido", challenge: "Jueguen 'Verdad o Reto' versión pareja. Solo 10 rondas.", emoji: "🎲" },
  { id: 96, category: "intimo", challenge: "Tomen un baño juntos o simplemente lávense los pies mutuamente.", emoji: "🛁" },
  { id: 97, category: "creatividad", challenge: "Graben un video contando su historia de amor en 1 minuto.", emoji: "🎥" },
  { id: 98, category: "crecimiento", challenge: "Practiquen juntos respiración profunda por 5 minutos. Solo respirar.", emoji: "🧘" },
  { id: 99, category: "comunicacion", challenge: "Cuéntale sobre un sueño (de dormir) que hayas tenido con ella/él.", emoji: "💤" },
  { id: 100, category: "aventura", challenge: "Aprendan juntos una receta nueva de YouTube y cocínenla hoy.", emoji: "📺" },
  { id: 101, category: "romantico", challenge: "Abrázale por la espalda cuando esté haciendo algo. Sin decir nada.", emoji: "🫂" },
  { id: 102, category: "divertido", challenge: "Hagan una apuesta pequeña sobre algo de hoy. ¿Quién gana?", emoji: "🤞" },
  { id: 103, category: "intimo", challenge: "Duerman hoy abrazados toda la noche. Intenten no soltarse.", emoji: "💑" },
  { id: 104, category: "creatividad", challenge: "Creen un apodo nuevo y cariñoso para el otro. Úsenlo todo el día.", emoji: "🏷️" },
  { id: 105, category: "crecimiento", challenge: "Agradézcanle a los padres del otro por haberle criado tan bien.", emoji: "👨‍👩‍👦" },
  { id: 106, category: "comunicacion", challenge: "Hagan un 'check-in emocional': del 1 al 10, ¿cómo se sienten hoy y por qué?", emoji: "📊" },
  { id: 107, category: "aventura", challenge: "Salgan a buscar el mejor pan de la zona. Prueben en 3 lugares.", emoji: "🍞" },
  { id: 108, category: "romantico", challenge: "Dile 'te quiero' de 5 formas diferentes hoy: gesto, palabra, acción, mirada, abrazo.", emoji: "💗" },
  { id: 109, category: "divertido", challenge: "Hagan un reto de cocina: cada uno tiene 15 minutos para hacer algo con lo que haya.", emoji: "⏱️" },
  { id: 110, category: "intimo", challenge: "Cuéntale el recuerdo más bonito que tienes de cuando eran novios.", emoji: "🕰️" },
  { id: 111, category: "creatividad", challenge: "Diseñen juntos cómo sería su casa ideal. Dibújenla.", emoji: "🏠" },
  { id: 112, category: "crecimiento", challenge: "Identifiquen una cosa que cada uno pueda hacer mejor por el otro esta semana.", emoji: "📈" },
  { id: 113, category: "comunicacion", challenge: "Cuéntale cuál es tu mayor sueño personal y cómo ella/él puede apoyarte.", emoji: "🚀" },
  { id: 114, category: "aventura", challenge: "Hagan algo que los dos tengan miedo de hacer. Juntos se puede.", emoji: "🎢" },
  { id: 115, category: "romantico", challenge: "Regálale una flor hoy. Si no hay flores, dibújale una.", emoji: "🌸" },
  { id: 116, category: "divertido", challenge: "Vean una película de risa juntos y coman palomitas (o rositas de maíz).", emoji: "🍿" },
  { id: 117, category: "intimo", challenge: "Peinen o acaricien el pelo del otro durante 10 minutos.", emoji: "💆" },
  { id: 118, category: "creatividad", challenge: "Escriban un cuento corto de 10 líneas alternando una línea cada uno.", emoji: "📝" },
  { id: 119, category: "crecimiento", challenge: "Hablen de cómo pueden ser un mejor equipo en las tareas del hogar.", emoji: "🧹" },
  { id: 120, category: "comunicacion", challenge: "Dile: 'Lo que más valoro de ti es...' y sé totalmente honesto/a.", emoji: "💎" },
  { id: 121, category: "aventura", challenge: "Busquen un mirador o azotea donde ver el cielo juntos esta noche.", emoji: "🔭" },
  { id: 122, category: "romantico", challenge: "Tómense una selfie besándose y guárdenla como fondo de pantalla.", emoji: "🤳" },
  { id: 123, category: "divertido", challenge: "Intenten hablar en otro idioma (inventado vale) por 5 minutos.", emoji: "🗣️" },
  { id: 124, category: "intimo", challenge: "Dile cuál fue el gesto más pequeño suyo que más te ha conmovido.", emoji: "🥹" },
  { id: 125, category: "creatividad", challenge: "Hagan una cápsula del tiempo: escriban predicciones para abrir en un año.", emoji: "🕳️" },
  { id: 126, category: "crecimiento", challenge: "Identifiquen un conflicto recurrente y propongan una solución juntos.", emoji: "🔧" },
  { id: 127, category: "comunicacion", challenge: "Jueguen al 'me gusta/no me gusta' sobre cosas del día a día.", emoji: "👍" },
  { id: 128, category: "aventura", challenge: "Salgan a caminar sin destino. Decidan en cada esquina si van izquierda o derecha.", emoji: "🚶" },
  { id: 129, category: "romantico", challenge: "Dile: 'Si pudiera elegirte de nuevo, te elegiría mil veces.'", emoji: "♾️" },
  { id: 130, category: "divertido", challenge: "Jueguen a quién conoce mejor al otro. Háganse 10 preguntas.", emoji: "🧠" },
  { id: 131, category: "intimo", challenge: "Acuéstense y escuchen juntos una canción con los ojos cerrados.", emoji: "🎵" },
  { id: 132, category: "creatividad", challenge: "Pinten con los dedos en un papel grande. Arte abstracto de pareja.", emoji: "🖐️" },
  { id: 133, category: "crecimiento", challenge: "Compartan lo que más les asusta de perder al otro.", emoji: "😰" },
  { id: 134, category: "comunicacion", challenge: "Hablen sobre su niñez: ¿cuál fue su juego favorito de pequeños?", emoji: "🧒" },
  { id: 135, category: "aventura", challenge: "Hagan un tour de comida callejera. Prueben al menos 3 puestos.", emoji: "🌮" },
  { id: 136, category: "romantico", challenge: "Dejen el teléfono en otra habitación y pasen 1 hora solo juntos.", emoji: "📵" },
  { id: 137, category: "divertido", challenge: "Hagan una batalla de almohadas épica. El ganador elige la cena.", emoji: "🛌" },
  { id: 138, category: "intimo", challenge: "Dense un beso largo y lento de al menos 15 segundos.", emoji: "💋" },
  { id: 139, category: "creatividad", challenge: "Creen un logo o escudo de armas para su relación.", emoji: "🛡️" },
  { id: 140, category: "crecimiento", challenge: "Hagan una lista de 'reglas de oro' para su relación. Mínimo 5.", emoji: "📜" },
  { id: 141, category: "comunicacion", challenge: "Cuéntale sobre la mejor lección de vida que te ha enseñado tu pareja.", emoji: "🎓" },
  { id: 142, category: "aventura", challenge: "Intenten ver un amanecer desde el Malecón o un lugar con vista al mar.", emoji: "🌊" },
  { id: 143, category: "romantico", challenge: "Cena romántica en casa: preparen algo sencillo pero con mucho amor.", emoji: "🍷" },
  { id: 144, category: "divertido", challenge: "Hagan un 'challenge' de TikTok juntos, de los que están de moda.", emoji: "📲" },
  { id: 145, category: "intimo", challenge: "Compartan un secreto inocente que nunca le hayan dicho.", emoji: "🤫" },
  { id: 146, category: "creatividad", challenge: "Diseñen su tatuaje ideal de pareja (en papel, no hace falta hacérselo).", emoji: "🖊️" },
  { id: 147, category: "crecimiento", challenge: "Establezcan una tradición semanal solo de ustedes. Decidan cuál.", emoji: "📅" },
  { id: 148, category: "comunicacion", challenge: "Dile qué música estabas escuchando cuando te enamoraste.", emoji: "🎹" },
  { id: 149, category: "aventura", challenge: "Visiten un parque, siéntense en un banco y observen a la gente pasar.", emoji: "🌳" },
  { id: 150, category: "romantico", challenge: "Escríbele un haiku de amor. Solo tres líneas: 5, 7, 5 sílabas.", emoji: "🌺" },
  { id: 151, category: "divertido", challenge: "Compitan a ver quién hace la mejor imitación de un reggaetón famoso.", emoji: "🎶" },
  { id: 152, category: "intimo", challenge: "Hablen de qué les hace sentir más vulnerables y cómo el otro puede ayudar.", emoji: "🫶" },
  { id: 153, category: "creatividad", challenge: "Decoren algo juntos: una pared, un cuaderno, una maceta.", emoji: "🪴" },
  { id: 154, category: "crecimiento", challenge: "Lean juntos los 5 lenguajes del amor y descubran el suyo.", emoji: "📖" },
  { id: 155, category: "comunicacion", challenge: "Hablen sobre qué harían si ganaran la lotería. ¿Qué cambiaría?", emoji: "💰" },
  { id: 156, category: "aventura", challenge: "Busquen la mejor pizza de la zona. Prueben y califiquen.", emoji: "🍕" },
  { id: 157, category: "romantico", challenge: "Mándale un sticker de amor a las 3pm sin motivo alguno.", emoji: "💌" },
  { id: 158, category: "divertido", challenge: "Jueguen a 'qué prefieres': opciones absurdas incluidas.", emoji: "🤔" },
  { id: 159, category: "intimo", challenge: "Tómense de las manos bajo la mesa hoy durante la comida.", emoji: "🤝" },
  { id: 160, category: "creatividad", challenge: "Hagan un mini álbum de fotos (digital o en papel) de sus mejores momentos.", emoji: "📸" },
  { id: 161, category: "crecimiento", challenge: "Practiquen decir 'lo siento' genuinamente. Incluso por cosas pequeñas.", emoji: "💐" },
  { id: 162, category: "comunicacion", challenge: "Pregúntale: '¿Hay algo que quieras que hagamos juntos que nunca hemos hecho?'", emoji: "🗨️" },
  { id: 163, category: "aventura", challenge: "Hagan una ruta de cafeterías: visiten 3 y elijan cuál tiene el mejor café.", emoji: "☕" },
  { id: 164, category: "romantico", challenge: "Al despertar, lo primero que digan sea: 'Buenos días, mi amor.'", emoji: "🌞" },
  { id: 165, category: "divertido", challenge: "Inventen una coreografía para una canción de reggaetón cubano.", emoji: "🕺" },
  { id: 166, category: "intimo", challenge: "Quédense despiertos hablando hasta tarde, como cuando empezaron.", emoji: "🌃" },
  { id: 167, category: "creatividad", challenge: "Creen un menú especial de 'restaurante en casa' con nombre y todo.", emoji: "📋" },
  { id: 168, category: "crecimiento", challenge: "Mediten juntos 10 minutos. Busquen una meditación guiada en YouTube.", emoji: "🧘‍♂️" },
  { id: 169, category: "comunicacion", challenge: "Dile cuál es la canción que más te recuerda a ella/él y por qué.", emoji: "🎵" },
  { id: 170, category: "aventura", challenge: "Hagan algo por la comunidad juntos: ayudar a un vecino, limpiar algo.", emoji: "🤲" },
  { id: 171, category: "romantico", challenge: "Dile: 'Gracias por estar. Tu presencia es mi lugar seguro.'", emoji: "🏡" },
  { id: 172, category: "divertido", challenge: "Jueguen a las adivinanzas cubanas. El que falle 3, lava los platos.", emoji: "🧩" },
  { id: 173, category: "intimo", challenge: "Hoy, solo comuníquense con gestos por 10 minutos. Sin palabras.", emoji: "🤐" },
  { id: 174, category: "creatividad", challenge: "Escriban juntos una 'Constitución de Pareja' con 7 artículos.", emoji: "📃" },
  { id: 175, category: "crecimiento", challenge: "Hablen sobre cómo pueden apoyar mejor los sueños del otro.", emoji: "🌠" },
  { id: 176, category: "comunicacion", challenge: "Cuéntale a tu pareja una historia de tu familia que no conozca.", emoji: "👨‍👩‍👧" },
  { id: 177, category: "aventura", challenge: "Intenten aprender algo nuevo juntos hoy: un truco de magia, un paso de baile.", emoji: "🪄" },
  { id: 178, category: "romantico", challenge: "Hagan juntos algo que hacían al principio de la relación y dejaron de hacer.", emoji: "🔄" },
  { id: 179, category: "divertido", challenge: "Compitan haciendo el pino o alguna acrobacia sencilla. ¡Cuidado!", emoji: "🤸" },
  { id: 180, category: "intimo", challenge: "Dile cuándo fue la última vez que te hizo sentir la persona más especial.", emoji: "👑" },
  { id: 181, category: "creatividad", challenge: "Hagan un calendario de pareja para el mes con actividades planificadas.", emoji: "🗓️" },
  { id: 182, category: "crecimiento", challenge: "Identifiquen una cosa tóxica que quieran eliminar de la relación.", emoji: "🚫" },
  { id: 183, category: "comunicacion", challenge: "Practiquen la escucha activa: 5 minutos cada uno hablando sin interrumpir.", emoji: "👂" },
  { id: 184, category: "aventura", challenge: "Descubran un atajo nuevo en su barrio caminando juntos.", emoji: "🛤️" },
  { id: 185, category: "romantico", challenge: "Al llegar a casa, salúdense como si no se vieran hace un mes.", emoji: "🏃‍♂️" },
  { id: 186, category: "divertido", challenge: "Hagan un concurso de peinados locos el uno al otro.", emoji: "💇" },
  { id: 187, category: "intimo", challenge: "Compartan qué parte del cuerpo del otro les parece más bonita.", emoji: "🌷" },
  { id: 188, category: "creatividad", challenge: "Inventen un idioma secreto con 10 palabras que solo ustedes entiendan.", emoji: "🔤" },
  { id: 189, category: "crecimiento", challenge: "Planifiquen un viaje soñado juntos, aunque sea solo en imaginación.", emoji: "✈️" },
  { id: 190, category: "comunicacion", challenge: "Cuéntale qué cosas de su personalidad te complementan perfectamente.", emoji: "🧩" },
  { id: 191, category: "aventura", challenge: "Hagan un maratón de películas cubanas. Al menos 2 seguidas.", emoji: "🎞️" },
  { id: 192, category: "romantico", challenge: "Prepárale un regalo hecho a mano, por sencillo que sea.", emoji: "🎀" },
  { id: 193, category: "divertido", challenge: "Jueguen a 'Simón dice' pero en versión pareja. Manda cada uno 5 rondas.", emoji: "🫡" },
  { id: 194, category: "intimo", challenge: "Dense un abrazo de oso bien fuerte y no se suelten hasta que quieran.", emoji: "🐻" },
  { id: 195, category: "creatividad", challenge: "Hagan un mapa de sus lugares favoritos juntos. Marquen los recuerdos.", emoji: "📍" },
  { id: 196, category: "crecimiento", challenge: "Escriban cada uno 3 promesas para el otro y léanlas en voz alta.", emoji: "🤝" },
  { id: 197, category: "comunicacion", challenge: "Dile: 'Si tuviera que enamorarme de nuevo, seguirías siendo tú.'", emoji: "💞" },
  { id: 198, category: "aventura", challenge: "Busquen un lugar nuevo para sentarse y hablar que nunca hayan probado.", emoji: "🪑" },
  { id: 199, category: "romantico", challenge: "Termina el día abrazados diciendo: 'Hoy fue un buen día porque estás aquí.'", emoji: "🌙" },
  { id: 200, category: "crecimiento", challenge: "Celebren algo hoy: un mes, una semana, o simplemente que están juntos.", emoji: "🎉" },
];
